import { createRoot } from 'react-dom/client'
import '@fontsource/instrument-serif/400.css'
import '@fontsource/instrument-serif/400-italic.css'
import '@fontsource/inter/400.css'
import '@fontsource/inter/500.css'
import '@fontsource/jetbrains-mono/400.css'
import '@fontsource/jetbrains-mono/500.css'
import '@fontsource/noto-serif-sc/400.css'
import '@fontsource/noto-serif-sc/600.css'
import './styles/base.css'
import './styles/stage.css'
import './styles/pages.css'
import './lib/smooth'
import { App } from './App'

document.documentElement.lang = localStorage.getItem('lang') === 'en' ? 'en' : 'zh-CN'
createRoot(document.getElementById('root')!).render(<App />)
